{% set name = "pathsim" %}
{% set version = "0.25.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/pathsim-{{ version }}.tar.gz
  sha256: e97e49b7d0012c07b61088f746722e6b4cd83e130c9731c4515882a522bd11f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm >=7.0.5
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.15
    - matplotlib-base >=3.1
    - scipy >=1.2
    - dill >=0.3.5

test:
  imports:
    - pathsim
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/milanofthe/pathsim
  summary: A differentiable block based hybrid system simulation framework.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - milanofthe
