{% set name = "pathsim" %}
{% set version = "0.12.3" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pathsim-{{ version }}.tar.gz
  sha256: 30bae6540e622af6456228f014124f728c64e734c1519f744f6b161b16b08e41

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm >=7.0.5
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.15
    - matplotlib-base >=3.1
    - scipy >=1.2
    - dill >=0.3.5

test:
  imports:
    - pathsim
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/pathsim/pathsim
  summary: A block based hybrid system simulation framework.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - milanofthe
