{% set name = "pathsim" %}
{% set version = "0.12.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pathsim-{{ version }}.tar.gz
  sha256: f22caeacf21b6031da92a82d9b5eae7fc109de61f4c51135453b9b088c710b17

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm >=7.0.5
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.15
    - matplotlib-base >=3.1
    - scipy >=1.2
    - dill >=0.3.5

test:
  imports:
    - pathsim
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/milanofthe/pathsim
  summary: A differentiable block based hybrid system simulation framework.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - milanofthe
